defmodule GeminiMock.Handler do
  @moduledoc false
  # NOTE: mock generated by an LLM, proceed with caution
  #  WebSock handler implementing the Gemini Live API protocol.
  #  Only supports AUDIO output modality.
  #
  #  State machine:
  #    - Awaiting setup  → receives {"setup": ...} → sends {"setupComplete": {}}
  #    - Ready           → receives client messages → sends serverContent / goAway

  @behaviour WebSock

  require Logger

  # ---------------------------------------------------------------------------
  # State
  # ---------------------------------------------------------------------------

  # setup_done           – true once setupComplete has been sent
  # go_away_after_ms     – nil or integer; triggers a GoAway timer on init
  # go_away_time_left_ms – duration value sent in GoAway message
  # response_delay_ms    – artificial latency before content responses
  # go_away_sent         – have we already sent the GoAway frame?

  # ---------------------------------------------------------------------------
  # WebSock callbacks
  # ---------------------------------------------------------------------------

  # ---------------------------------------------------------------------------
  # Scripted mode (driven per-test through GeminiMock.Scenario)
  # ---------------------------------------------------------------------------
  #
  # Every decoded client frame is forwarded to the owning test process and the
  # server only sends what the test pushes, so the test controls the exact
  # frame sequence and timing. The `setup` frame is auto-acknowledged with
  # `setupComplete` (unless auto_setup: false) because the session blocks on it
  # while connecting.

  @impl WebSock
  def init(%{mode: :scripted} = state) do
    send(state.test_pid, {:gemini_mock, :connected, self()})
    {:ok, state}
  end

  def init(opts) do
    state = %{
      setup_done: false,
      close_error: Map.get(opts, :close_error),
      go_away_after_ms: Map.get(opts, :go_away_after_ms),
      go_away_time_left_ms: Map.get(opts, :go_away_time_left_ms, 10_000),
      response_delay_ms: Map.get(opts, :response_delay_ms, 0),
      go_away_sent: false
    }

    if state.go_away_after_ms do
      Process.send_after(self(), :send_go_away, state.go_away_after_ms)
    end

    {:ok, state}
  end

  @impl WebSock
  def handle_in({data, opcode: opcode}, %{mode: :scripted} = state)
      when opcode in [:text, :binary] do
    case Jason.decode(data) do
      {:ok, frame} ->
        send(state.test_pid, {:gemini_mock, :frame, self(), frame})

        case frame do
          %{"setup" => _setup} when state.auto_setup ->
            {:push, [{:text, Jason.encode!(%{"setupComplete" => %{}})}], state}

          _other ->
            {:ok, state}
        end

      {:error, reason} ->
        Logger.warning("GeminiMock: failed to decode incoming frame – #{inspect(reason)}")
        {:ok, state}
    end
  end

  def handle_in({data, opcode: opcode}, state) when opcode in [:text, :binary] do
    case Jason.decode(data) do
      {:ok, message} ->
        process_message(message, state)

      {:error, reason} ->
        Logger.warning("GeminiMock: failed to decode incoming frame – #{inspect(reason)}")
        {:ok, state}
    end
  end

  def handle_in(_frame, state), do: {:ok, state}

  @impl WebSock
  def handle_control(_frame, state), do: {:ok, state}

  @impl WebSock
  def handle_info({:gemini_mock, :push, frames}, %{mode: :scripted} = state) do
    {:push, Enum.map(frames, &{:text, Jason.encode!(&1)}), state}
  end

  def handle_info({:gemini_mock, :close, code, reason}, %{mode: :scripted} = state) do
    {:stop, :normal, {code, reason}, state}
  end

  def handle_info(:send_go_away, state) do
    time_left_s = state.go_away_time_left_ms / 1000

    Logger.info("GeminiMock: sending GoAway (timeLeft=#{time_left_s}s)")

    go_away =
      Jason.encode!(%{
        "goAway" => %{"timeLeft" => "#{time_left_s}s"}
      })

    {:push, [{:text, go_away}], %{state | go_away_sent: true}}
  end

  def handle_info(_msg, state), do: {:ok, state}

  @impl WebSock
  def terminate(reason, %{mode: :scripted} = state) do
    send(state.test_pid, {:gemini_mock, :closed, self(), reason})
    :ok
  end

  def terminate(reason, _state) do
    Logger.debug("GeminiMock: connection terminated – #{inspect(reason)}")
    :ok
  end

  # ---------------------------------------------------------------------------
  # Message routing
  # ---------------------------------------------------------------------------

  defp process_message(%{"setup" => setup}, %{close_error: {code, reason}} = state) do
    Logger.warning(
      "GeminiMock: setup received but rejecting, model=#{setup["model"]}, code=#{code}"
    )

    {:stop, :normal, {code, reason}, state}
  end

  defp process_message(%{"setup" => setup}, state) do
    Logger.debug("GeminiMock: setup received, model=#{setup["model"]}")
    {:push, [{:text, Jason.encode!(%{"setupComplete" => %{}})}], %{state | setup_done: true}}
  end

  defp process_message(%{"clientContent" => _content}, %{setup_done: true} = state) do
    delay(state.response_delay_ms)
    {:push, build_audio_responses(false), state}
  end

  defp process_message(%{"realtimeInput" => input}, %{setup_done: true} = state) do
    delay(state.response_delay_ms)
    has_audio = Map.has_key?(input, "audio")

    # Housekeeping-only messages like {"audioStreamEnd": true} must not
    # trigger a response; otherwise the audio-source EOS sent at the end of
    # every pipeline creates a spurious extra response cycle.
    if has_audio or Map.has_key?(input, "text") do
      {:push, build_audio_responses(has_audio), state}
    else
      {:ok, state}
    end
  end

  defp process_message(msg, state) do
    Logger.debug("GeminiMock: unhandled message keys=#{inspect(Map.keys(msg))}")
    {:ok, state}
  end

  # Multi-frame audio response that mirrors the real Gemini Live API sequence:
  #   1. (optional) inputTranscription  – only when responding to audio input
  #   2. Thinking chunk                 – thought=true text part
  #   3. Audio chunk                    – 100 ms of PCM silence at 24 kHz
  #   4. outputTranscription            – transcript of the audio chunk
  #   5. generationComplete             – signals end of the turn
  defp build_audio_responses(include_input_transcript) do
    alias Membrane.RawAudio

    format = %RawAudio{
      sample_format: :s16le,
      sample_rate: 24_000,
      channels: 1
    }

    silence = RawAudio.silence(format, RawAudio.bytes_to_time(1920, format))
    silence_b64 = Base.encode64(silence)

    input_transcript_frames =
      if include_input_transcript do
        [
          {:text,
           Jason.encode!(%{
             "serverContent" => %{
               "inputTranscription" => %{"text" => "hello"}
             }
           })}
        ]
      else
        []
      end

    thinking_frame =
      {:text,
       Jason.encode!(%{
         "serverContent" => %{
           "modelTurn" => %{
             "role" => "model",
             "parts" => [%{"thought" => true, "text" => "thinking"}]
           }
         }
       })}

    audio_frame =
      {:text,
       Jason.encode!(%{
         "serverContent" => %{
           "modelTurn" => %{
             "role" => "model",
             "parts" => [
               %{
                 "inlineData" => %{
                   "mimeType" => "audio/pcm;rate=24000",
                   "data" => silence_b64
                 }
               }
             ]
           }
         }
       })}

    output_transcript_frame =
      {:text,
       Jason.encode!(%{
         "serverContent" => %{
           "outputTranscription" => %{"text" => "ok"}
         }
       })}

    generation_complete_frame =
      {:text,
       Jason.encode!(%{
         "serverContent" => %{
           "generationComplete" => true
         }
       })}

    input_transcript_frames ++
      [thinking_frame, audio_frame, output_transcript_frame, generation_complete_frame]
  end

  @spec delay(ms :: integer()) :: any()
  defp delay(0), do: :ok
  defp delay(ms) when is_integer(ms) and ms > 0, do: Process.sleep(ms)
end
