defmodule GeminiMock.Router do
  @moduledoc false
  # NOTE: mock generated by an LLM, proceed with caution
  use Plug.Router

  plug(:match)
  plug(:dispatch)

  # Accept any path under /ws/ – this covers both the Gemini API path:
  #   /ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContent
  # and the Vertex AI path:
  #   /ws/google.cloud.aiplatform.v1beta1.LlmBidiService/BidiGenerateContent
  match "/ws/*_path" do
    conn = Plug.Conn.fetch_query_params(conn)
    api_key = Map.get(conn.query_params, "key")

    opts =
      case scripted_lookup(api_key) do
        {test_pid, scenario_opts} ->
          # Scripted mode: the API key is a per-test token registered by
          # GeminiMock.Scenario.setup!/1; the handler is driven by that test.
          %{
            mode: :scripted,
            test_pid: test_pid,
            auto_setup: Map.get(scenario_opts, :auto_setup, true)
          }

        nil ->
          close_error =
            case api_key do
              "mock-api-key" ->
                nil

              nil ->
                {1008,
                 "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API c"}

              _invalid ->
                {1007, "API key not valid. Please pass a valid API key."}
            end

          opts = build_handler_opts(conn)
          if close_error, do: Map.put(opts, :close_error, close_error), else: opts
      end

    WebSockAdapter.upgrade(conn, GeminiMock.Handler, opts, timeout: 120_000)
  end

  match _ do
    send_resp(conn, 404, "Not found")
  end

  defp scripted_lookup(nil), do: nil

  defp scripted_lookup(api_key) do
    case Registry.lookup(GeminiMock.Registry, {:scripted, api_key}) do
      [{test_pid, scenario_opts}] -> {test_pid, scenario_opts}
      [] -> nil
    end
  end

  # Parse per-connection query params for test scenarios.
  # Query params allow individual tests to customize behavior without restarting the server.
  defp build_handler_opts(conn) do
    go_away_ms =
      case Map.get(conn.query_params, "go_away_after_ms") do
        nil -> nil
        ms_str -> String.to_integer(ms_str)
      end

    delay_ms =
      conn.query_params
      |> Map.get("response_delay_ms", "0")
      |> String.to_integer()

    time_left_ms =
      conn.query_params
      |> Map.get("go_away_time_left_ms", "10000")
      |> String.to_integer()

    %{
      go_away_after_ms: go_away_ms,
      go_away_time_left_ms: time_left_ms,
      response_delay_ms: delay_ms
    }
  end
end
