defmodule Membrane.Gemini.Events.Thinking do
  @moduledoc """
  Event holding the thinking prompt generated by Gemini.
  """

  @derive Membrane.EventProtocol

  @type t :: %__MODULE__{
          text: String.t()
        }

  @enforce_keys [:text]

  defstruct @enforce_keys
end
