defmodule Membrane.Gemini.MockWebSocket do
  @moduledoc false
  # NOTE: mock generated by an LLM, proceed with caution
  # WebSocket client that connects to the local GeminiMock server instead of
  # the real Gemini Live API. Implements the same interface as
  # Gemini.Client.WebSocket so it can be injected via the :websocket_module
  # option in Gemini.Live.Session.

  require Logger

  @mock_host ~c"localhost"
  @mock_path "/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContent"

  @connect_timeout 10_000
  @upgrade_timeout 5_000

  defstruct [:gun_pid, :stream_ref, status: :connecting]

  @type t :: %__MODULE__{
          gun_pid: pid() | nil,
          stream_ref: reference() | nil,
          status: :connecting | :connected | :closing | :closed
        }

  @doc """
  Connects to the local mock server via plain HTTP WebSocket.
  Passes the API key from the GEMINI_API_KEY environment variable as a query parameter.
  """
  @spec connect(atom(), keyword()) :: {:ok, t()} | {:error, term()}
  def connect(_auth_strategy, opts) do
    port = Keyword.get(opts, :mock_port, 4003)
    gun_opts = %{protocols: [:http], transport: :tcp}

    case :gun.open(@mock_host, port, gun_opts) do
      {:ok, pid} ->
        case :gun.await_up(pid, @connect_timeout) do
          {:ok, _protocol} ->
            # Include API key as query parameter
            api_key = System.get_env("GEMINI_API_KEY", "")
            path_with_key = "#{@mock_path}?key=#{api_key}"

            headers = [{"content-type", "application/json"}]
            stream_ref = :gun.ws_upgrade(pid, path_with_key, headers, %{})

            receive do
              {:gun_upgrade, ^pid, ^stream_ref, ["websocket"], _headers} ->
                {:ok, %__MODULE__{gun_pid: pid, stream_ref: stream_ref, status: :connected}}

              {:gun_response, ^pid, ^stream_ref, :nofin, status, _headers} ->
                # Read the response body for non-final responses
                body = read_response_body(pid, stream_ref)
                :gun.close(pid)
                {:error, {:upgrade_failed, status, body}}

              {:gun_response, ^pid, ^stream_ref, :fin, status, _headers} ->
                :gun.close(pid)
                {:error, {:upgrade_failed, status, []}}

              {:gun_error, ^pid, ^stream_ref, reason} ->
                :gun.close(pid)
                {:error, {:upgrade_error, reason}}
            after
              @upgrade_timeout ->
                :gun.close(pid)
                {:error, :upgrade_timeout}
            end

          {:error, reason} ->
            :gun.close(pid)
            {:error, {:connection_failed, reason}}
        end

      {:error, reason} ->
        {:error, {:open_failed, reason}}
    end
  end

  @doc "Sends a JSON-encodable message over the WebSocket."
  @spec send(t(), map()) :: :ok | {:error, term()}
  def send(%__MODULE__{status: :connected, gun_pid: pid, stream_ref: ref}, message)
      when is_map(message) do
    json = Jason.encode!(message)
    :gun.ws_send(pid, ref, {:text, json})
    :ok
  catch
    :error, reason -> {:error, reason}
  end

  def send(%__MODULE__{status: status}, _message) do
    {:error, {:not_connected, status}}
  end

  @doc "Blocks until a JSON message is received or the timeout elapses."
  @spec receive(t(), timeout()) :: {:ok, map()} | {:error, term()}
  def receive(%__MODULE__{gun_pid: pid, stream_ref: ref}, timeout \\ 60_000) do
    receive do
      {:gun_ws, ^pid, ^ref, {:text, data}} ->
        Jason.decode(data)

      {:gun_ws, ^pid, ^ref, {:binary, data}} ->
        Jason.decode(data)

      {:gun_ws, ^pid, ^ref, {:close, code, reason}} ->
        {:error, {:closed, code, reason}}

      {:gun_down, ^pid, _protocol, reason, _} ->
        {:error, {:connection_down, reason}}

      {:gun_error, ^pid, ^ref, reason} ->
        {:error, reason}

      {:gun_error, ^pid, reason} ->
        {:error, reason}
    after
      timeout -> {:error, :timeout}
    end
  catch
    :exit, reason -> {:error, {:exit, reason}}
  end

  @doc "Closes the WebSocket connection."
  @spec close(t()) :: :ok
  def close(%__MODULE__{gun_pid: nil}), do: :ok

  def close(%__MODULE__{gun_pid: pid, stream_ref: ref, status: :connected}) do
    :gun.ws_send(pid, ref, :close)
    :gun.close(pid)
    :ok
  end

  def close(%__MODULE__{gun_pid: pid}) do
    :gun.close(pid)
    :ok
  end

  # Helper function to read the response body from gun_data messages
  defp read_response_body(pid, stream_ref, timeout \\ 1_000) do
    receive do
      {:gun_data, ^pid, ^stream_ref, :fin, data} ->
        data

      {:gun_data, ^pid, ^stream_ref, :nofin, data} ->
        data <> read_response_body(pid, stream_ref, timeout)
    after
      timeout -> ""
    end
  end
end
