defmodule Membrane.Gemini.ThinkingEvent do
  @moduledoc """
  Event holding the thinking prompt generated by Gemini.
  """

  @derive Membrane.EventProtocol

  @enforce_keys [:text]

  defstruct @enforce_keys
end
